version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    build: ../uptrader/
    container_name: backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  database:
  static_value:
  media_value: